### ISSUE TITLE
If ifconfig unavailable hanlon_init fails

### ISSUE THREAD

**Issue by jcpowermac** [csc/Hanlon#362]
ifconfig (and its related packages tools - net-tools) are depreciated.  `/core/config/server.rb` should be modified to support `ip a` including `ifconfig`.

```
root@eaa06ccdb078:/home/hanlon# ./hanlon_init 
      ** Notice: The native BSON extension was not loaded. **

      For optimal performance, use of the BSON extension is recommended.

      To enable the extension make sure ENV['BSON_EXT_DISABLED'] is not set
      and run the following command:

        gem install bson_ext

      If you continue to receive this message after installing, make sure that
      the bson_ext gem is in your load path.

Project Hanlon (ver 2.2.0+33-g9a00e76)
Hanlon - Copyright (C) 2012 EMC Corporation
         Copyright (C) 2012-2013 Puppet Labs LLC
         Copyright (C) 2014 Computer Sciences Corporation


Setting initial environment for Project Hanlon

Creating server configuration file...
/home/hanlon/core/config/server.rb:57:in ``': No such file or directory - /sbin/ifconfig (Errno::ENOENT)
	from /home/hanlon/core/config/server.rb:57:in `get_interfaces'
	from /home/hanlon/core/config/server.rb:218:in `get_initial_hanlon_subnets'
	from /home/hanlon/core/config/server.rb:158:in `defaults'
	from /home/hanlon/core/config/common.rb:54:in `initialize'
	from ./hanlon_init:74:in `new'
	from ./hanlon_init:74:in `create_hanlon_config_file'
	from ./hanlon_init:61:in `run'
	from ./hanlon_init:206:in `<main>'

```

**Comment by sankarvema** [comment]
Was thinking about it. ifconfig also needs change in model layer
