### ISSUE TITLE
hanlon_init fails on OSX

### ISSUE THREAD

**Issue by mkristiansen** [csc/Hanlon#430]
Pull latest master branch
cd to repo directory
./hanlon_init

```
/usr/local/opt/rbenv/versions/2.2.3/lib/ruby/2.2.0/ipaddr.rb:559:in `in6_addr': invalid address (IPAddr::InvalidAddressError)
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/2.2.0/ipaddr.rb:496:in `initialise'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/2.2.0/ipaddr.rb:416:in `new'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/2.2.0/ipaddr.rb:416:in `mask!'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/2.2.0/ipaddr.rb:503:in `initialise'
	from /Users/<User>/Code/rb.Hanlon/core/config/server.rb:276:in `new'
	from /Users/<User>/Code/rb.Hanlon/core/config/server.rb:276:in `block in get_initial_hanlon_subnets'
	from /Users/<User>/Code/rb.Hanlon/core/config/server.rb:267:in `map'
	from /Users/<User>/Code/rb.Hanlon/core/config/server.rb:267:in `get_initial_hanlon_subnets'
	from /Users/<User>/Code/rb.Hanlon/core/config/server.rb:208:in `defaults'
	from /Users/<User>/Code/rb.Hanlon/core/config/common.rb:54:in `initialise'
```

Failure arises due to default (?) kernel value of :bsd, convert_from_hex? does not know that :bsd requires conversion.

```
def self.convert_from_hex?(kernel)
    kernels_to_convert = [:sunos, :openbsd, :netbsd, :freebsd, :darwin, :"hp-ux", :"gnu/kfreebsd", :dragonfly, :aix]
    kernels_to_convert.include?(kernel)
  end
```
```
  def self.get_single_interface_value(interface, label)
    # search for 'ifconfig'
    interface_info_cmd = find_executable0('ifconfig', nil)
    # if 'ifconfig' was found, parse the output of that command to obtain the
    # requested field
    if interface_info_cmd
      # in this case, need to parse the output of the
      # 'ifconfig' command (which varies from kernel to
      # kernel) to find the value that was requested
      REGEX_MAP.each { |kernel, map|
        regex = map[label.to_sym]
        tmp1 = []
        output = %x{#{interface_info_cmd} #{interface}}
        if interface != /^lo[0:]?\d?/
          output.split('\n').each do |s|
            if s =~ regex
              value = $1
              if label == 'netmask' && convert_from_hex?(kernel)
                value = value.scan(/../).collect do |byte| byte.to_i(16) end.join('.')
              end
              tmp1.push(value)
            end
          end
        end
        if tmp1
          value = tmp1.shift
          return value if value
        end
      }
    end
```

The following on-line change will correct the problem
`if label == 'netmask' && convert_from_hex?(Facter.value(:kernel).downcase.to_sym)`

**Comment by mtnbikenc** [comment]
Closed by #432
